[workspace]
resolver = "2"
members = ["crates/core", "crates/app-slint"]

[workspace.package]
edition = "2021"
version = "0.1.0"
rust-version = "1.89"

[workspace.dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["clock", "std"] }
rusqlite = { version = "0.40", features = ["bundled"] }
thiserror = "2"
tracing = "0.1.44"
tempfile = "3.27"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
